[2022-02-21 16:54:53,033] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: test_path.get_path manual__2022-02-21T16:54:52.285900+00:00 [queued]>
[2022-02-21 16:54:53,042] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: test_path.get_path manual__2022-02-21T16:54:52.285900+00:00 [queued]>
[2022-02-21 16:54:53,042] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-21 16:54:53,042] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-21 16:54:53,042] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-21 16:54:53,053] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): get_path> on 2022-02-21 16:54:52.285900+00:00
[2022-02-21 16:54:53,059] {standard_task_runner.py:52} INFO - Started process 161 to run task
[2022-02-21 16:54:53,063] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'test_path', 'get_path', 'manual__2022-02-21T16:54:52.285900+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpzgpmfny7', '--error-file', '/tmp/tmph3il8mtc']
[2022-02-21 16:54:53,063] {standard_task_runner.py:77} INFO - Job 55: Subtask get_path
[2022-02-21 16:54:53,113] {logging_mixin.py:109} INFO - Running <TaskInstance: test_path.get_path manual__2022-02-21T16:54:52.285900+00:00 [running]> on host 7c24e16e6467
[2022-02-21 16:54:53,166] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=test_path
AIRFLOW_CTX_TASK_ID=get_path
AIRFLOW_CTX_EXECUTION_DATE=2022-02-21T16:54:52.285900+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-21T16:54:52.285900+00:00
[2022-02-21 16:54:53,166] {logging_mixin.py:109} INFO - /opt/***
[2022-02-21 16:54:53,167] {python.py:175} INFO - Done. Returned value was: None
[2022-02-21 16:54:53,177] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=test_path, task_id=get_path, execution_date=20220221T165452, start_date=20220221T165453, end_date=20220221T165453
[2022-02-21 16:54:53,195] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-21 16:54:53,221] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
