[2022-02-21 16:53:12,906] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: test_path.get_path manual__2022-02-21T16:53:12.571686+00:00 [queued]>
[2022-02-21 16:53:12,928] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: test_path.get_path manual__2022-02-21T16:53:12.571686+00:00 [queued]>
[2022-02-21 16:53:12,928] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-21 16:53:12,928] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-21 16:53:12,928] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-21 16:53:12,948] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): get_path> on 2022-02-21 16:53:12.571686+00:00
[2022-02-21 16:53:12,963] {standard_task_runner.py:52} INFO - Started process 86 to run task
[2022-02-21 16:53:12,973] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'test_path', 'get_path', 'manual__2022-02-21T16:53:12.571686+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp0qbwhah1', '--error-file', '/tmp/tmpmps7rox7']
[2022-02-21 16:53:12,973] {standard_task_runner.py:77} INFO - Job 16: Subtask get_path
[2022-02-21 16:53:13,049] {logging_mixin.py:109} INFO - Running <TaskInstance: test_path.get_path manual__2022-02-21T16:53:12.571686+00:00 [running]> on host 7c24e16e6467
[2022-02-21 16:53:13,121] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=test_path
AIRFLOW_CTX_TASK_ID=get_path
AIRFLOW_CTX_EXECUTION_DATE=2022-02-21T16:53:12.571686+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-21T16:53:12.571686+00:00
[2022-02-21 16:53:13,121] {logging_mixin.py:109} INFO - /opt/***
[2022-02-21 16:53:13,121] {python.py:175} INFO - Done. Returned value was: None
[2022-02-21 16:53:13,141] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=test_path, task_id=get_path, execution_date=20220221T165312, start_date=20220221T165312, end_date=20220221T165313
[2022-02-21 16:53:13,179] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-21 16:53:13,220] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
